### ISSUE TITLE
Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by marcosvidolin** [MattRoss34/spring-cloud-config#22]
ERROR Error reading cloud config: Protocol "https:" not supported. Expected "http:"

To fix: Just update the spring-cloud-client version.

**Comment by huanghai21** [comment]
checked the source codes, the version has been updated to "^1.0.0" in this [commit](https://github.com/MattRoss34/spring-cloud-config/commit/3fa12f81fd337ada6ec026f2572b065b983cfa62#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

but it still not published to the npm registry yet.

HI, @MattRoss34 
Would you please to do the publish action with the latest codes, thank you

**Comment by MattRoss34** [comment]
V2.0.1 published.  Thanks for the heads up.
