### ISSUE TITLE
Refresh endpoint or interval 

### ISSUE THREAD

**Issue by deeravi** [MattRoss34/spring-cloud-config#50]
Spring cloud config includes a actuator endpoint - '/actuator/refresh' to enable refreshing configs within the application context. This library works great for fetching configs but I was unable to find a similar mechanism to get refreshed values. 
This endpoint would help in fetching configs without having to restart or redeploy the application.
Any plans for the above ?

**Comment by MattRoss34** [comment]
@deeravi I think you can achieve this on your own while still utilizing this library.  If your application is running express (or any web framework), just add a route for `/actuator/refresh`, call the `load` function.
```
app.post('/actuator/refresh', function (req, res) {
  springCloudConfig.load(configOptions).then...
})
```
This will re-load, save, and return the latest configuration properties. 
 You can then either use the returned config object, or refer back to it later using `springCloudConfig.instance()`.
